export const roomsData = [
  {
    title: "HABITACION CLASICA",
    images: [
      "https://i0.wp.com/terraandinahotel.com/wp-content/uploads/2025/12/Clasica-mat-1.jpg?fit=500%2C333&ssl=1",
      "https://i0.wp.com/terraandinahotel.com/wp-content/uploads/2025/12/Clasica-bano-1.jpg?fit=500%2C333&ssl=1",
      "https://i0.wp.com/terraandinahotel.com/wp-content/uploads/2025/12/clasica-doble-1.webp?fit=500%2C333&ssl=1",
    ],
    services: [
    ],
  },
  {
    title: "HABITACION PREMIUM",
    titleService: "SERVICIOS ADICIONALES",
    images: [
      "https://i0.wp.com/terraandinahotel.com/wp-content/uploads/2025/12/Premium-Triple-1.webp?fit=500%2C333&ssl=1",
      "https://i0.wp.com/terraandinahotel.com/wp-content/uploads/2025/12/premium-matrimonial-1.webp?fit=500%2C333&ssl=1",
      "https://i0.wp.com/terraandinahotel.com/wp-content/uploads/2025/12/Premium-triple-bano.webp?fit=500%2C333&ssl=1",
      "https://i0.wp.com/terraandinahotel.com/wp-content/uploads/2025/12/Premium-familiar-1.jpg?fit=500%2C333&ssl=1",
      "https://i0.wp.com/terraandinahotel.com/wp-content/uploads/2025/12/Premium-familiar-bano1-1.jpg?fit=500%2C333&ssl=1",
      "https://i0.wp.com/terraandinahotel.com/wp-content/uploads/2025/12/Premium-bano-1.jpg?fit=500%2C333&ssl=1",
    ],
    services: [
      "Espejo de aumento para maquillarse o afeitarse",
      'LBaños remodelados con porcelanato italiano de piso a techo',
      "Batas",
      "Pantuflas",
      'Toalla de Algodon',
      "Selección de Amenities de baño mejorada",
      "Teléfono en el baño",
      "Ubicación preferencial",

      "Habitaciones conectadas (con solicitud previa)",
      'LED de 50" Smart TV',
      "Traslados aeropuerto-hotel o viceversa de cortesía",
      "Minibar",
      'Colchas de pluma de ganso blanco "Pacific Coast"',
      "Botella de agua de bienvenida",
      "Habitaciones más amplias",
      "Kit de infusiones",
    ],
  },
  {
    title: "HABITACION JUNIOR SUITE",
    titleService: "SERVICIOS ADICIONALES",

    images: [
      "https://i0.wp.com/terraandinahotel.com/wp-content/uploads/2025/12/Junior-Suite3.jpg?fit=500%2C333&ssl=1",
      "https://i0.wp.com/terraandinahotel.com/wp-content/uploads/2025/12/Junior-Suite-bano2.webp?fit=500%2C333&ssl=1",
      "https://i0.wp.com/terraandinahotel.com/wp-content/uploads/2025/12/Junior-Suite2.webp?fit=500%2C333&ssl=1",
      "https://i0.wp.com/terraandinahotel.com/wp-content/uploads/2025/12/Junior-Suite1.webp?fit=500%2C333&ssl=1",
      "https://i0.wp.com/terraandinahotel.com/wp-content/uploads/2025/12/Junior-Suite-bano1.webp?fit=500%2C333&ssl=1",
    ],
    services: [
      "Espejo de aumento para maquillarse o afeitarse",
      'LBaños remodelados con porcelanato italiano de piso a techo',
      "Batas",
      "Pantuflas",
      'Toalla de Algodon',
      "Selección de Amenities de baño mejorada",
      "Teléfono en el baño",
      "Ubicación preferencial",

      "Habitaciones conectadas (con solicitud previa)",
      'LED de 50" Smart TV',
      "Traslados aeropuerto-hotel o viceversa de cortesía",
      "Minibar",
      'Colchas de pluma de ganso blanco "Pacific Coast"',
      "Botella de agua de bienvenida",
      "Habitaciones más amplias",
      "Kit de infusiones",
    ],
  },
  {
    title: "SUITE",
    titleService: "SERVICIOS ADICIONALES",

    images: [
      "https://i0.wp.com/terraandinahotel.com/wp-content/uploads/2025/12/Suite10.webp?fit=500%2C333&ssl=1",
      "https://i0.wp.com/terraandinahotel.com/wp-content/uploads/2025/12/suite6.webp?fit=500%2C333&ssl=1",
      "https://i0.wp.com/terraandinahotel.com/wp-content/uploads/2025/12/Suite-1-1.jpg?fit=500%2C333&ssl=1",
      "https://i0.wp.com/terraandinahotel.com/wp-content/uploads/2025/12/Suite2.jpg?fit=500%2C333&ssl=1",
      "https://i0.wp.com/terraandinahotel.com/wp-content/uploads/2025/12/Suite3.webp?fit=500%2C333&ssl=1",
      "https://i0.wp.com/terraandinahotel.com/wp-content/uploads/2025/12/suite4.webp?fit=500%2C333&ssl=1",
      "https://i0.wp.com/terraandinahotel.com/wp-content/uploads/2025/12/suite5.jpg?fit=500%2C333&ssl=1",
      "https://i0.wp.com/terraandinahotel.com/wp-content/uploads/2025/12/Suite7.jpg?fit=500%2C333&ssl=1",
      "https://i0.wp.com/terraandinahotel.com/wp-content/uploads/2025/12/Suite9.webp?fit=500%2C333&ssl=1",
    ],
   services: [
      "Espejo de aumento para maquillarse o afeitarse",
      'LBaños remodelados con porcelanato italiano de piso a techo',
      "Batas",
      "Pantuflas",
      'Toalla de Algodon',
      "Selección de Amenities de baño mejorada",
      "Teléfono en el baño",
      "Ubicación preferencial",

      "Habitaciones conectadas (con solicitud previa)",
      'LED de 50" Smart TV',
      "Traslados aeropuerto-hotel o viceversa de cortesía",
      "Minibar",
      'Colchas de pluma de ganso blanco "Pacific Coast"',
      "Botella de agua de bienvenida",
      "Habitaciones más amplias",
      "Kit de infusiones",
    ],
  },
];
