export const roomsData = [
  {
    title: "HABITACION CLASICA",
    images: [
      "/images/rooms/Clasica-mat-1.webp",
      "/images/rooms/Clasica-bano-1.webp",
      "/images/rooms/clasica-doble-1.webp",
    ],
    services: [
    ],
    servicesEN: [
    ],
  },
  {
    title: "HABITACION PREMIUM",
    titleService: "SERVICIOS ADICIONALES",
    images: [
      "/images/rooms/premium-matrimonial-1.webp",
      "/images/rooms/Premium-Triple-1.webp",
      "/images/rooms/Premium-familiar-1.webp",
      "/images/rooms/Premium-familiar-bano1-1.webp",
      "/images/rooms/Premium-bano-1.webp",
      "/images/rooms/Ameneties-premium.webp",
      "/images/rooms/Premium-triple1.webp",
      "/images/rooms/Premium-twin.webp",
    ],
    services: [
      "Espejo de aumento para maquillarse o afeitarse",
      'Baños remodelados con porcelanato italiano de piso a techo',
      "Batas",
      "Pantuflas",
      'Toalla de Algodon',
      "Selección de Amenities de baño mejorada",
      "Teléfono en el baño",
      "Ubicación preferencial",

      "Habitaciones conectadas (con solicitud previa)",
      'LED de 50" Smart TV',
      "Traslados aeropuerto-hotel o viceversa de cortesía",
      "Minibar",
      'Colchas de pluma de ganso blanco "Pacific Coast"',
      "Botella de agua de bienvenida",
      "Habitaciones más amplias",
      "Kit de infusiones",
    ],
    
    servicesEN: [
      "Magnifying mirror for make-up or shaving",
      'Bathrooms with floor to ceiling Italian porcelain tiles',
      "Bathrobes",
      "Slippers",
      'Cotton towels',
      "Upgrades bathroom amenities",
      "In-bathroom Telephone",
      "Preferred Location",
      "Larger Rooms",

      "Connecting Rooms",
      'Optional a la carte breakfast at no extra cost',
      "LED 50'' Smart TV",
      "Heating",
      'Friobar',
      "Complimentary airport-hotel transfers or viceversa",
      "Hyperclean® Pacific Coast® White Goose Down Comforter 600 Fill",
      "Welcome bottle of water",
      "Infusion kit",
    ],
  },
  {
    title: "HABITACION JUNIOR SUITE",
    titleService: "SERVICIOS ADICIONALES",

    images: [
      "/images/rooms/Ameneties-premium.webp",
      "/images/rooms/Junior-Suite2.webp",
      "/images/rooms/Junior-Suite1.webp",
      "/images/rooms/Junior-Suite-bano1.webp",
      "/images/rooms/Junior-Suite-bano2.webp",
    ],
    services: [
      "Espejo de aumento para maquillarse o afeitarse",
      'Baños remodelados con porcelanato italiano de piso a techo',
      "Batas",
      "Pantuflas",
      'Toalla de Algodon',
      "Selección de Amenities de baño mejorada",
      "Teléfono en el baño",
      "Ubicación preferencial",
      "Habitaciones más amplias",

      "Kit de infusiones",
      'Desayuno a la carta sin cargo adicional',
      "LED de 50'' Smart TV",
      "Minibar",
      'Tableros de baño de mármol de "Carrara, Italia"',
      "Colchas de pluma de ganso blanco 'Pacific Coast'",
      "Botella de agua de bienvenida",
      "Traslados aeropuerto-hotel o viceversa de cortesia",
    ],
    servicesEN: [
      "Magnifying mirror for make-up or shaving",
      'Bathrooms with floor to ceiling Italian porcelain tiles',
      "Bathrobes",
      "Slippers",
      'Cotton towels',
      "Upgrades bathroom amenities",
      "In-bathroom Telephone",
      "Preferred Location",
      "Larger Rooms",

      "Complimentary airport-hotel transfers or viceversa",
      'Infusion Kit',
      "Optional a la carte breakfast at no extra cost",
      "LED 50'' Smart TV",
      'Heating',
      "Friobar",
      "Italy’s Carrara marble bathroom counter tops",
      "Hyperclean® Pacific Coast® White Goose Down Comforter 600 Fill",
      "Welcome bottle of water",

    ],
  },
  {
    title: "SUITE",
    titleService: "SERVICIOS ADICIONALES",

    images: [
      "/images/rooms/Ameneties-premium.webp",
      "/images/rooms/Suite10.webp",
      "/images/rooms/Suite-1-1.webp",
      "/images/rooms/Suite2.webp",
      "/images/rooms/Suite3.webp",
      "/images/rooms/suite4.webp",
      "/images/rooms/suite5.webp",
      "/images/rooms/Suite7.webp",
      "/images/rooms/Suite9.webp",
    ],
   services: [
      "Espejo de aumento para maquillarse o afeitarse",
      'LBaños remodelados con porcelanato italiano de piso a techo',
      "Batas",
      "Pantuflas",
      'Toalla de Algodon',
      "Selección de Amenities de baño mejorada",
      "Teléfono en el baño",
      "Ubicación preferencial",
      "Habitaciones más amplias",

      "Bañera de hidromasajes de gran tamaño",
      'LED de 50" Smart TV',
      "Minibar",
      "Servicio de lavandería a disposición",
      'Botella de agua de bienvenida',
      "Microondas",
      "Kit de infusiones",
      "Traslados aeropuerto-hotel o viceversa de cortesía",
    ],

    servicesEN: [
      "Magnifying mirror for make-up or shaving",
      'Bathrooms with floor to ceiling Italian porcelain tiles',
      "Bathrobes",
      "Slippers",
      'Cotton towels',
      "Upgrades bathroom amenities",
      "In-bathroom Telephone",
      "Preferred Location",
      "Larger Rooms",
      "Complimentary airport-hotel transfers or viceversa",

      "Infusion Kit",
      'Optional a la carte breakfast at no extra cost',
      "LED 50'' Smart TV",
      "Heating",
      'Friobar',
      "Laundry Service",
      "Welcome bottle of water",
      "Microondas",
      "Oversized soaking tub with Hydro-massage",
      "Italy’s Carrara marble bathroom counter tops",
    ],
  },
];
